var numero=12;
console.log("el valor del numero es:"+ numero);
let nombre="Ana Graciela Cano Mera";
var edad=35;
var salario=6000000;
var hijos=2;
console.log("La información de la desarrolladora es la siguiente:" +nombre+" , su edad es:"+edad+" su salario será de:"+salario+" y tendrá el siguiente número de hijos:"+hijos);

let femenino=true
let masculino=false
console.log("Mi genero es femenino " + femenino + " masculino " +masculino);




